from pathlib import Path
import json
ROOT = Path(__file__).resolve().parents[1]
def replace(file, old, new):
    p = ROOT / file
    s = p.read_text()
    if old not in s: raise RuntimeError('PATCH_BASE_MISMATCH: ' + file)
    p.write_text(s.replace(old, new))
def put(file, content):
    p=ROOT/file
    p.parent.mkdir(parents=True,exist_ok=True)
    p.write_text(content)
replace('src/mcp.mjs', 'pending.clear(); input.pause(); };', 'pending.clear(); engine.close?.(); input.pause(); };')
replace('src/mcp.mjs', "else if (message.params.name === 'jev_route') value = await layer.route(args, { signal: controller.signal });", "else if (message.params.name === 'jev_route') { if (!isObject(args)) fail('INVALID_REQUEST'); const { trace, ...request } = args; value = await layer.route(request, { signal: controller.signal, trace }); }")
replace('src/mcp.mjs', "else if (message.params.name === 'jev_filter') value = await layer.filter(args, { signal: controller.signal });", "else if (message.params.name === 'jev_filter') { if (!isObject(args)) fail('INVALID_REQUEST'); const { trace, ...request } = args; value = await layer.filter(request, { signal: controller.signal, trace }); }")
replace('src/mcp.mjs', "else if (message.params.name === 'jev_observe')", "else if (message.params.name === 'jev_record') {\n        if (!isObject(args) || Object.keys(args).some(k => !['kind', 'data'].includes(k)) || !isObject(args.data)) fail('INVALID_REQUEST');\n        if (args.kind === 'host') value = engine.recordHost(args.data);\n        else if (args.kind === 'outcome') value = engine.recordOutcome(args.data);\n        else fail('INVALID_REQUEST');\n      }\n      else if (message.params.name === 'jev_observe')")
replace('tests/mcp.test.mjs', "'jev_observe']", "'jev_observe', 'jev_record']")
replace('workers/laya_worker.py', '    records = []', "    if any(p.is_symlink() for p in [root, *root.parents]):\n        raise ValueError('MODEL_SYMLINK_REFUSED')\n    records = []")
replace('src/training/dataset.mjs', 'import { fail }', "import { DEFAULTS, PURPOSES, fail } from '../constants.mjs';\nimport { validateRequest, wireRequest } from '../contracts.mjs';\n// Canonical validation shares the inference input contract.\nimport { fail as unusedFail }")
replace('src/training/dataset.mjs', "import { fail as unusedFail } from '../constants.mjs';\n", '')
replace('src/training/dataset.mjs', 'safeContent, targetDistribution, validateTarget', 'safeContent, targetDistribution, validateTarget, validateProvenance, only, id')
replace('src/training/dataset.mjs', '  for (const s of samples) union(`task:${s.task_id}`, `input:${s.request_hash}`);', '  for (const s of samples) {\n    for (const task of s.task_ids) union(`task:${task}`, `input:${s.request_hash}`);\n    union(`input:${s.request_hash}`, `state:${digest(s.state)}`);\n  }')
replace('src/training/dataset.mjs', '          task_id: d.trace.task_id, snapshot_id: d.trace.snapshot_id, request_hash:', '          task_id: d.trace.task_id, snapshot_id: d.trace.snapshot_id, task_ids: [d.trace.task_id], snapshot_ids: [d.trace.snapshot_id], request_hash:')
replace('src/training/dataset.mjs', '        excluded.duplicates++; const first = unique.get(s.sample_id);', '        excluded.duplicates++; const first = unique.get(s.sample_id);\n        first.task_ids = [...new Set([...first.task_ids, ...s.task_ids])].sort();\n        first.snapshot_ids = [...new Set([...first.snapshot_ids, ...s.snapshot_ids])].sort();')
replace('src/training/dataset.mjs', 'connected task_id OR identical request_hash; deterministic 80/10/10 group split', 'connected ALL task IDs OR identical request/state hash; deterministic 80/10/10 group split')
replace('src/training/dataset.mjs', '    safeContent(s); validateTarget(s.question, s.target.value);', "    safeContent(s);\n    only(s, ['schema_version','sample_id','task_id','snapshot_id','task_ids','snapshot_ids','request_hash','purpose','state','question_id','question','target','label_source','label_confidence','label_confidence_is_calibrated','evaluation_policy_version','provenance','raw_refs','group_id','split'], ['sample_id','task_ids','snapshot_ids','request_hash','provenance','raw_refs','question','target']);\n    if (!Array.isArray(s.provenance) || !s.provenance.length || !Array.isArray(s.task_ids) || !s.task_ids.length || !Array.isArray(s.snapshot_ids) || !s.snapshot_ids.length || !PURPOSES.includes(s.purpose)) fail('INVALID_CANONICAL_DATASET');\n    s.provenance.forEach(validateProvenance); s.task_ids.forEach(id); id(s.task_id);\n    if (!s.task_ids.includes(s.task_id) || !s.snapshot_ids.includes(s.snapshot_id) || s.snapshot_ids.some(x => !HASH.test(x)) || !HASH.test(s.request_hash) || !HASH.test(s.group_id)) fail('INVALID_CANONICAL_DATASET');\n    validateRequest({purpose:s.purpose,risk:'routine',state:s.state,questions:{[s.question_id]:s.question}}, DEFAULTS);\n    if (!Number.isFinite(s.label_confidence) || s.label_confidence < EVALUATION_POLICY.minLabelConfidence || s.label_confidence > 1 || !['objective','human','mixed_independent'].includes(s.label_source)) fail('INVALID_CANONICAL_DATASET');\n    for (const key of ['decisions','outcomes']) { if (!Array.isArray(s.raw_refs[key]) || !s.raw_refs[key].length) fail('INVALID_CANONICAL_DATASET'); s.raw_refs[key].forEach(id); }\n    validateTarget(s.question, s.target.value);")
replace('src/training/dataset.mjs', "'laya-typed-decisions-json-v1'", "'laya-typed-decisions-json-v2'")
replace('src/training/dataset.mjs', "export function exportDataset(store, version, format = 'laya') {", "// Match official Agent._to_internal json.dumps(list): ensure_ascii=True, comma-space.\nconst pythonString = s => JSON.stringify(s).replace(/[\u007f-\uffff]/g, c => '\\u' + c.charCodeAt(0).toString(16).padStart(4, '0'));\nexport function layaQuestion(sample) {\n  const q = wireRequest({state:sample.state,questions:{[sample.question_id]:sample.question}}, 'export').questions[sample.question_id];\n  return {...q, instructions: '[' + q.instructions.map(pythonString).join(', ') + ']'};\n}\nexport function exportDataset(store, version, format = 'laya') {")
replace('src/training/dataset.mjs', 'questions: JSON.stringify({ [s.question_id]: s.question })', 'questions: JSON.stringify({ [s.question_id]: layaQuestion(s) })')
replace('src/training/dataset.mjs', 'upstream_contract: LAYA_UPSTREAM, evaluation_policy_version:', "upstream_contract: LAYA_UPSTREAM, input_transform: 'wire-request-v1 plus official json.dumps(instructions)', evaluation_policy_version:")
replace('src/training/dataset.mjs', 'outcomes.find(e => e.data.final)?.data', 'outcomes.find(e => e.data.final && e.data.executed)?.data')
p=ROOT/'package.json'
v=json.loads(p.read_text())
v['version']='0.3.0'
v['exports'].update({'./training':'./src/training/store.mjs','./dataset':'./src/training/dataset.mjs','./training/evaluate':'./src/training/evaluate.mjs','./training/host':'./src/training/host.mjs'})
v['scripts']['demo:training']='node examples/training-pipeline.mjs'
p.write_text(json.dumps(v,indent=2)+'\n')
p=ROOT/'package-lock.json'
v=json.loads(p.read_text())
v['version']='0.3.0'
v['packages']['']['version']='0.3.0'
p.write_text(json.dumps(v,indent=2)+'\n')
replace('src/constants.mjs', "VERSION = '0.2.0'", "VERSION = '0.3.0'")
replace('src/inference.mjs', 'export function createLayaClient() {', 'export function createLayaClient({ spawnImpl = spawn } = {}) {')
replace('src/inference.mjs', 'const process = spawn(l.python,', 'const process = spawnImpl(l.python,')
replace('src/inference.mjs', "identity.device.split(':')[0] !== l.device", "typeof identity.device !== 'string' || identity.device.split(':')[0] !== l.device")
replace('src/training/store.mjs', "      return append('decisions', structuredClone(data), data.decision_id);", "      return lock(() => {\n        if (expectedTicket !== undefined && (expectedTicket === null || ticket() !== expectedTicket)) return { stored: false, reason: 'CAPTURE_CONSENT_CHANGED' };\n        return appendUnlocked('decisions', structuredClone(data), data.decision_id);\n      });")
replace('src/engine.mjs', 'provider: result.provider ?? null, model:', 'captureStored: result.trainingCapture?.stored ?? null, captureReason: result.trainingCapture?.reason ?? null,\n          provider: result.provider ?? null, model:')
replace('src/metrics.mjs', '  const observations = events.filter', "  const jevDecisions = decisions.filter(e => (e.provider ?? 'jev') === 'jev');\n  const providerActivity = Object.fromEntries(['jev', 'laya'].map(provider => {\n    const rows = decisions.filter(e => (e.provider ?? 'jev') === provider);\n    const inference = rows.filter(e => (e.inferenceCalls ?? e.networkCalls ?? 0) > 0);\n    const normal = ['ACCEPTED','LOW_CONFIDENCE','UNQUALIFIED_PROVIDER','SHADOW','MODE_CHANGED','POLICY_CHANGED','PROVIDER_CHANGED','CANCELLED'];\n    return [provider, { requests:rows.length, inferenceCalls:inference.reduce((s,e)=>s+(e.inferenceCalls ?? e.networkCalls),0), networkCalls:rows.reduce((s,e)=>s+(e.networkCalls||0),0),\n      accepted:rows.filter(e=>e.apply).length, hostFallbacks:rows.filter(e=>e.mode==='on' && !e.apply).length, errors:inference.filter(e=>!normal.includes(e.reason)).length,\n      inputTokens:tokens(rows,'usage','inputTokens'), outputTokens:tokens(rows,'usage','outputTokens'), missingUsageCalls:inference.filter(e=>e.usage?.inputTokens==null||e.usage?.outputTokens==null).length,\n      latencyMs:{p50:percentile(inference.map(e=>e.elapsedMs).filter(Number.isFinite),.5),p95:percentile(inference.map(e=>e.elapsedMs).filter(Number.isFinite),.95)} }];\n  }));\n  const observations = events.filter")
replace('src/metrics.mjs', '    accepted: decisions.filter(e => e.apply).length,', '    inferenceCalls: decisions.reduce((s,e)=>s+(e.inferenceCalls ?? e.networkCalls ?? 0),0), providerActivity,\n    accepted: decisions.filter(e => e.apply).length,')
replace('src/metrics.mjs', "jevReportedTokens: { input: tokens(decisions, 'usage', 'inputTokens'), output: tokens(decisions, 'usage', 'outputTokens'),", "jevReportedTokens: { input: tokens(jevDecisions, 'usage', 'inputTokens'), output: tokens(jevDecisions, 'usage', 'outputTokens'),")
replace('src/metrics.mjs', 'missingUsageCalls: decisions.filter(e => e.networkCalls', 'missingUsageCalls: jevDecisions.filter(e => e.networkCalls')
replace('README.md', '# Jev Agent Control\n', '# Jev Agent Control\n\n## v0.3: Jev/Laya와 선택적 학습 데이터 수집\n\n기존 Jev API 경로와 OFF/SHADOW/ON을 유지하면서 **공식 Laya Python worker를 선택 가능한 provider**로 추가했다. `provider status|jev|laya`로 로컬 설정을 선택한다. 자동 provider cascade나 모델 학습은 없다.\n\n**Training Capture 기본 OFF.** 켠 경우에만 최소 비식별 Decision → 별도 Outcome → versioned Evaluation → 검증된 canonical Dataset → Laya export를 저장소 밖 사용자 전용 경로에 축적한다. operational telemetry는 계속 content-free다. Decision은 정답이 아니며, agreement도 정확도가 아니다.\n\n```sh\njev-control training capture status\njev-control training capture on     # 사용자가 명시적으로 승인한 경우\njev-control training capture off\njev-control dataset stats\njev-control dataset validate\njev-control dataset build\njev-control dataset export --version <dataset-hash> --format laya\nnode examples/training-pipeline.mjs # 키/모델 없는 검증용 예제\n```\n\n실제 source schema, 결과 연결법, 보안 경계 및 공식 Laya export 계약은 [TRAINING_DATA.md](docs/TRAINING_DATA.md)를 확인한다. `jev_record`는 weak host evidence만 기록하며 MCP에서 human/runner 권위를 만들지 않는다. 실제 Laya 모델·MPS·native host 성능과 fine-tuning은 fixture 테스트와 별도 검증 대상이다.\n\n아래 기존 설치·모드·키 절차는 기본 Jev 경로에 계속 적용된다. Laya 설정에는 TypeSafe 키가 필요하지 않으며, Python·모델 다운로드/전처리는 명시적 별도 준비 작업이다.\n\n')
p=ROOT/'docs/ARCHITECTURE.md'
s=p.read_text()
p.write_text(s+'## v0.3 implementation boundary\n\n`inference.mjs` selects Jev or an optional official Laya worker. `engine.mjs` preserves one control policy and emits canonical provenance. `training/schema,store,evaluate,dataset,host,cli.mjs` separate immutable raw evidence from derived supervision. CLI/MCP only expose explicit controls and bounded weak-evidence recording. No online learning or automatic checkpoint promotion. The earlier v0.2 feature descriptions below remain applicable to generic control, with TypeSafe-specific transport/readiness now owned by its adapter. See [TRAINING_DATA.md](TRAINING_DATA.md) for the normative v0.3 contracts.\n\n')
p=ROOT/'docs/TESTING.md'
s=p.read_text()
p.write_text(s+'## v0.3 verification\n\nRun `node scripts/check.mjs`, `node --test tests/*.test.mjs`, `node bin/jev-control.mjs smoke`, `node examples/fast-path.mjs`, and `node examples/training-pipeline.mjs`. Optional Python boundary tests: `python3 -m unittest discover -s tests -p "test_laya_worker.py"`. They use no real model or network. Added tests cover capture OFF/consent epochs, provenance, delayed outcomes, weak-source boundaries, per-purpose evidence, orphan/corrupt events, dedup split leakage, immutable/reproducible datasets, official JSON-string export, provider metrics, worker UTF-8/termination and MCP/CLI integration. Passing these does not verify actual Laya weights/MPS, native Codex/Claude, paid API or downstream model quality. Earlier counts below describe v0.2 only; use the current test/CI summary for current counts.\n\n')
p=ROOT/'SECURITY.md'
s=p.read_text()
p.write_text(s+'## v0.3 training capture is a separate opt-in data boundary\n\nOperational telemetry still stores no raw state, questions or answer values. Explicitly enabled Training Capture may persist bounded sanitized content to private files OUTSIDE Git. It is OFF by default, is not encrypted storage, and performs no upload/training. Every export row is screened; regex detection is not complete DLP. Capture permission must cover the complete inference interval. Model comparisons need explicit remote consent. MCP outcomes are always weak host-review evidence, not runner/human attestations. Laya starts only a locally configured Python/runtime/checkpoint with allowlisted environment, no inherited API/HF secrets, no shell, no network download, and no automatic CPU fallback acceptance. Same-OS-user tampering is outside the threat boundary. See [docs/TRAINING_DATA.md](docs/TRAINING_DATA.md).\n\n')
p=ROOT/'AGENTS.md'
s=p.read_text()
p.write_text(s+'## Current v0.3 development/operation requirements\n\nContinue the existing working branch; do not discard local edits or merge main without instruction. Follow docs/TRAINING_DATA.md for provider/evidence APIs. Do not enable capture/provider modes merely because installation passes. Never read raw training files into the model by default. Record minimal trace IDs and later outcomes; use jev_record only as weak host evidence. Do not claim to be a human or trusted runner through CLI to manufacture training labels. Actual runner integrations collect their own checks; label assertions are question-specific and independent. No online training, automatic provider fallback, or checkpoint promotion. Run new training pipeline demo and offline tests in addition to existing checks.\n\n')
p=ROOT/'skills/jev-control/SKILL.md'
s=p.read_text()
p.write_text(s+'\n## Provider and opt-in capture controls\n\nWhen the user explicitly requests these actions, use the same scripts/run.mjs with `provider status|jev|laya`, `training capture status|on|off`, `dataset stats|validate|build`, or `dataset export --version HASH --format laya|canonical`. Never turn capture ON yourself, dump raw samples into chat, run training, or publish datasets. Provider selection requires prepared local configuration; do not download Python/models during a decision. Default capture is OFF.\n')
p=ROOT/'skills/jev-decisions/SKILL.md'
s=p.read_text()
p.write_text(s+'\n## Optional evidence capture\n\nIf explicitly enabled, attach minimal `trace.task_id`, `snapshot_id`, and optionally `comparison_id` to typed requests. After work, use `jev_record` with kind=outcome and a minimal evidence object matching src/training/schema.mjs; omit unmeasured metrics and raw outputs. MCP records are always weak host_review. A baseline uses kind=host and is not ground truth. Do not turn agreement, build success, or your own confidence into a label for unrelated intent/difficulty/worker questions. Never run a CLI command pretending your judgment is a human correction or trusted runner. Do not read training raw files to influence a blind baseline.\n')
replace('src/installer.mjs', 'tool_timeout_sec = 15', 'tool_timeout_sec = 210')
p=ROOT/'.gitignore'
s=p.read_text()
p.write_text(s+'\n# Optional Python runtime test caches\n__pycache__/\n*.pyc\n*.pyo\n')
replace('tests/training-helpers.mjs', "runtimeVersion: '0.3.4', device: 'cpu', ...patch", "runtimeVersion: '0.3.4', device: 'cpu', startupTimeoutMs: 1000, idleTimeoutMs: 1000, ...patch")
replace('.github/workflows/ci.yml', '      - run: node examples/fast-path.mjs', '      - run: node examples/fast-path.mjs\n      - run: node examples/training-pipeline.mjs\n      - run: python3 -m unittest discover -s tests -p test_laya_worker.py')
