from pathlib import Path
import json
ROOT = Path(__file__).resolve().parents[1]
def replace(file, old, new):
    p = ROOT / file
    s = p.read_text()
    if old not in s: raise RuntimeError('PATCH_BASE_MISMATCH: ' + file)
    p.write_text(s.replace(old, new))
replace('src/training/schema.mjs', "'downstream-evidence-v1'", "'downstream-evidence-v2'")
replace('src/training/schema.mjs', "    if (typeof v === 'string') {", "    if (typeof v === 'string') {\n      const trimmed = v.trim();\n      if ((trimmed.startsWith('{') && trimmed.endsWith('}')) || (trimmed.startsWith('[') && trimmed.endsWith(']'))) {\n        let parsed; try { parsed = JSON.parse(trimmed); } catch { /* ordinary text */ }\n        if (parsed && typeof parsed === 'object') { if (containsSensitiveData(parsed, key)) fail('TRAINING_SENSITIVE_OR_OVERSIZED'); visit(parsed, depth + 1); }\n      }")
replace('src/training/schema.mjs', '  for (const key of Object.keys(p)) text(p[key], 200);', "  for (const key of Object.keys(p)) text(p[key], 200);\n  if (p.provider === 'laya' && !HASH.test(p.checkpoint)) fail('INVALID_TRAINING_SCHEMA');")
replace('src/training/schema.mjs', "      if (q.type === 'choice' && a.probabilities[a.value] + 1e-9 < Math.max(...Object.values(a.probabilities))) fail('INVALID_TRAINING_SCHEMA');", "      if (q.type === 'choice' && a.probabilities[a.value] + 1e-9 < Math.max(...Object.values(a.probabilities))) fail('INVALID_TRAINING_SCHEMA');\n      if (a.selectedProbability !== undefined && (q.type !== 'choice' || a.selectedProbability !== a.probabilities[a.value])) fail('INVALID_TRAINING_SCHEMA');")
replace('src/training/schema.mjs', "  if (d.arm === 'shadow' && d.apply)", "  if ((d.arm === 'shadow' || d.mode === 'shadow') && d.apply)")
replace('src/training/schema.mjs', "    if (c.exit_status !== undefined && !Number.isInteger(c.exit_status)) fail('INVALID_TRAINING_SCHEMA');", "    if (c.exit_status !== undefined && (!Number.isInteger(c.exit_status) || c.passed !== (c.exit_status === 0))) fail('INVALID_TRAINING_SCHEMA');")
replace('src/training/store.mjs', '    const parent = path.dirname(dir);', "    if (fs.existsSync(path.join(dir, 'HEAD')) && fs.existsSync(path.join(dir, 'objects')) && fs.existsSync(path.join(dir, 'refs'))) fail('TRAINING_IN_REPOSITORY_REFUSED');\n    const parent = path.dirname(dir);")
replace('src/training/store.mjs', "only(c, ['version', 'trainingCapture'], ['version', 'trainingCapture']);", "only(c, ['version', 'trainingCapture', 'generation'], ['version', 'trainingCapture']);\n    if (c.generation !== undefined && !UUID.test(c.generation)) fail('INVALID_TRAINING_CONFIG');")
replace('src/training/store.mjs', '  function status() {', "  function ticket() { try { const c = config(); return c.trainingCapture ? (c.generation ?? 'legacy-enabled') : null; } catch { return null; } }\n  function status() {")
replace('src/training/store.mjs', 'encode({ version: 1, trainingCapture: enabled })', 'encode({ version: 1, trainingCapture: enabled, generation: randomUUID() })')
replace('src/training/store.mjs', "  function decision(data, { secret = '' } = {}) {", "  function decision(data, { secret = '', expectedTicket } = {}) {")
replace('src/training/store.mjs', '      safeContent(data, secret); validateDecision(data);', "      if (expectedTicket !== undefined && (expectedTicket === null || ticket() !== expectedTicket)) return { stored: false, reason: 'CAPTURE_CONSENT_CHANGED' };\n      safeContent(data, secret); validateDecision(data);")
replace('src/training/store.mjs', '    const events = [], invalid = [], duplicates = new Map();', '    const events = [], invalid = [], duplicates = new Map(); let totalBytes = 0;')
replace('src/training/store.mjs', '          const e = validateEvent(JSON.parse(readText(path.join(dir, name), { privateFile: true, maxBytes: 49152 })));', "          const source = readText(path.join(dir, name), { privateFile: true, maxBytes: 49152 });\n          totalBytes += Buffer.byteLength(source);\n          if (totalBytes > 64 * 1024 * 1024) fail('TRAINING_SNAPSHOT_TOO_LARGE');\n          const e = validateEvent(JSON.parse(source));")
replace('src/training/store.mjs', '        } catch (error) { invalid.push({ kind, code: errorCode(error) }); }', "        } catch (error) { if (errorCode(error) === 'TRAINING_SNAPSHOT_TOO_LARGE') throw error; invalid.push({ kind, code: errorCode(error) }); }")
replace('src/training/store.mjs', "    outsideGit(root); safeContent(JSON.parse(contents.trim().split('\\n')[0] || '{}'));", "    outsideGit(root);\n    if (typeof contents !== 'string' || Buffer.byteLength(contents) > 64 * 1024 * 1024) fail('DATASET_TOO_LARGE');\n    for (const line of contents.split('\\n').filter(x => x.trim())) safeContent(JSON.parse(line));")
replace('src/training/store.mjs', '{ root, home, status, config, setCapture', '{ root, home, status, config, ticket, setCapture')
replace('src/engine.mjs', 'import { CAPTURE_VERSION', "import { recordHost } from './training/host.mjs';\nimport { CAPTURE_VERSION")
replace('src/engine.mjs', '    let config, settings, request, normalized', '    const captureTicket = training.ticket();\n    let config, settings, request, normalized')
replace('src/engine.mjs', '{ secret: key });', '{ secret: key, expectedTicket: captureTicket });')
replace('src/engine.mjs', '    return { active, comparison_id, observers:', "    if (status().policyRevision !== initial.policyRevision || signal?.aborted) {\n      active.apply = false; active.source = 'host'; active.answers = {}; active.reason = 'COMPARISON_CONTEXT_CHANGED';\n    }\n    return { active, comparison_id, observers:")
replace('src/engine.mjs', "recordOutcome: input => training.outcome(input, { trust: 'host' })", "recordOutcome: input => training.outcome(input, { trust: 'host' }),\n    recordHost: input => recordHost(training, input)")
replace('src/inference.mjs', 'import { spawn }', "import { StringDecoder } from 'node:string_decoder';\nimport { spawn }")
replace('src/inference.mjs', "  let child, starting, readyIdentity, identityKey, buffer = '', idle;", "  let child, starting, readyIdentity, identityKey, buffer = '', idle, decoder = new StringDecoder('utf8');")
replace('src/inference.mjs', "readyIdentity = null; buffer = '';", "readyIdentity = null; buffer = ''; decoder = new StringDecoder('utf8');")
replace('src/inference.mjs', "      buffer += chunk.toString('utf8');", '      buffer += decoder.write(chunk);')
replace('src/cli.mjs', "  if (values.help || command === 'help') {", "  try {\n  if (values.help || command === 'help') {")
replace('src/cli.mjs', "if (command !== 'off' && !getCredential(home, env).key) fail('NO_API_KEY');", "if (command !== 'off' && !engine.status().ready) fail(engine.status().provider === 'laya' ? 'LAYA_NOT_READY' : 'NO_API_KEY');")
replace('src/cli.mjs', "if (!getCredential(home, env).key) fail('NO_API_KEY');", "if (!engine.status().ready) fail(engine.status().provider === 'laya' ? 'LAYA_NOT_READY' : 'NO_API_KEY');")
replace('src/cli.mjs', "['ACCEPTED', 'LOW_CONFIDENCE', 'SHADOW']", "['ACCEPTED', 'LOW_CONFIDENCE', 'UNQUALIFIED_PROVIDER', 'SHADOW']")
replace('src/cli.mjs', "  fail('UNKNOWN_COMMAND');\n}", "  fail('UNKNOWN_COMMAND');\n  } finally { if (command !== 'mcp') engine.close(); }\n}")
replace('src/features-cli.mjs', 'import { createControlLayer }', "import { createDecisionEngine } from './engine.mjs';\nimport { createControlLayer }")
replace('src/features-cli.mjs', '  const layer = createControlLayer({ home, env });', '  const engine = createDecisionEngine({ home, env });\n  const layer = createControlLayer({ home, env, engine });\n  try {')
replace('src/features-cli.mjs', "else if (command === 'route') print(await layer.route(await jsonStdin()));", "else if (command === 'route') { const { trace, ...request } = await jsonStdin(); print(await layer.route(request, { trace })); }")
replace('src/features-cli.mjs', '    const result = await layer.filter(await jsonStdin());', '    const { trace, ...request } = await jsonStdin();\n    const result = await layer.filter(request, { trace });')
replace('src/features-cli.mjs', '  return true;\n}', '  return true;\n  } finally { engine.close(); }\n}')
replace('src/features-cli.mjs', 'Classifier-inspired features (TypeSafe API only)', 'Classifier-inspired features (explicit Jev or local Laya provider)')
replace('src/mcp.mjs', 'import { decisionSchema }', "import { traceSchema } from './training/schema.mjs';\nimport { decisionSchema }")
replace('src/mcp.mjs', 'const protocolVersions', 'const withTrace = schema => ({ ...schema, properties: { ...schema.properties, trace: traceSchema } });\nconst protocolVersions')
replace('src/mcp.mjs', 'inputSchema: decisionSchema', 'inputSchema: withTrace(decisionSchema)')
replace('src/mcp.mjs', 'inputSchema: routeSchema', 'inputSchema: withTrace(routeSchema)')
replace('src/mcp.mjs', 'inputSchema: filterSchema', 'inputSchema: withTrace(filterSchema)')
replace('src/mcp.mjs', 'OFF never calls TypeSafe', 'OFF never invokes a provider')
replace('src/mcp.mjs', 'with one TypeSafe call', 'with one selected-provider inference')
replace('src/mcp.mjs', '];\n\n/** Minimal', "  { name: 'jev_record', description: 'Append a minimal host baseline or outcome only when training capture is explicitly enabled. All MCP outcomes are weak host-review evidence; cannot assert runner/human authority, read datasets, enable capture, train, or promote a model.', inputSchema: {\n    type: 'object', additionalProperties: false, required: ['kind', 'data'], properties: { kind: { type: 'string', enum: ['host', 'outcome'] }, data: { type: 'object' } },\n  }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false } },\n];\n\n/** Minimal")
